# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

#image: debian



stages:
    - build
    - clean


job:build:
    stage: build
    script:
        - cd AJAC_S8
        - make clean all
    when: always




job:clean:
    stage: clean
    script: echo "make clean"
    when: always
    allow_failure: true
